import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
void main(){runApp(ChangeNotifierProvider(create: (_)=>AppData(), child: const MyApp()));}
class AppData extends ChangeNotifier{
  String admin='+263780195262';
  String name=''; String phone=''; bool logged=false;
  bool get isAdmin=>phone.contains('780195262');
  List<Map<String,dynamic>> chats=[{'name':'Tinashe','last':'Hi','pic':'T','msgs':[]}];
  void login(n,p){name=n; phone=p; logged=true; notifyListeners();}
}
class MyApp extends StatelessWidget{const MyApp({super.key}); @override Widget build(BuildContext c){return MaterialApp(home: Consumer<AppData>(builder: (_,d,__)=>
d.logged? const ChatList(): const Login()));}}
class Login extends StatefulWidget{const Login({super.key}); @override State<Login> createState()=>_L();}
class _L extends State<Login>{final n=TextEditingController(); final p=TextEditingController(); @override Widget build(BuildContext c){return Scaffold(backgroundColor: const Color(0xFF009739), body: Center(child: Card(margin: const EdgeInsets.all(20), child: Padding(padding: const EdgeInsets.all(20), child: Column(mainAxisSize: MainAxisSize.min, children: [TextField(controller: n, decoration: const InputDecoration(labelText: 'Name *', border: OutlineInputBorder())), const SizedBox(height:8), TextField(controller: p, decoration: const InputDecoration(labelText: 'Phone +263780195262 Admin', border: OutlineInputBorder())), const SizedBox(height:12), ElevatedButton(onPressed: (){Provider.of<AppData>(context,listen:false).login(n.text,p.text);}, child: const Text('LOGIN'))])))));}}
class ChatList extends StatelessWidget{const ChatList({super.key}); @override Widget build(BuildContext c){var d=Provider.of<AppData>(c); return Scaffold(appBar: AppBar(title: Text('ZimChat Admin ${d.isAdmin?"ADMIN":""}'), backgroundColor: const Color(0xFF009739)), body: ListView.builder(itemCount: d.chats.length, itemBuilder: (_,i)=>ListTile(leading: CircleAvatar(child: Text(d.chats[i]['pic'])), title: Text(d.chats[i]['name']), subtitle: Text(d.chats[i]['last']), onTap: (){Navigator.push(c, MaterialPageRoute(builder: (_)=>ChatOpen(i:i)));})), floatingActionButton: FloatingActionButton(onPressed: (){showDialog(context: c, builder: (_)=>AlertDialog(title: const Text('Invite Link'), content: const Text('https://zimchat.co.zw/join/263780195262\nShare via WhatsApp/SMS - No data via Nearby')));}, child: const Icon(Icons.person_add)));}
class ChatOpen extends StatefulWidget{final int i; const ChatOpen({super.key, required this.i}); @override State<ChatOpen> createState()=>_CO();}
class _CO extends State<ChatOpen>{final m=TextEditingController(); @override Widget build(BuildContext c){var d=Provider.of<AppData>(c); return Scaffold(appBar: AppBar(title: Text(d.chats[widget.i]['name'])), body: Column(children: [Expanded(child: ListView(children: [const Text('Swipe mic to record like WhatsApp, tap camera to share')])), Row(children: [IconButton(icon: const Icon(Icons.camera_alt), onPressed: (){ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content: Text('📷 Camera opened - take pic and share')));}), Expanded(child: TextField(controller: m, decoration: const InputDecoration(hintText: 'Message', border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(25)))))), IconButton(icon: const Icon(Icons.send), onPressed: (){if(m.text.isNotEmpty){d.chats[widget.i]['last']=m.text; d.notifyListeners(); m.clear();}}), const CircleAvatar(backgroundColor: Color(0xFF009739), child: Icon(Icons.mic, color: Colors.white))])]));}}
